
##### ESP32-C3 Supermini pinout #####################################################################
# status_led (on GPIO8)
# Pin mappings:
# Silkscreen pin	Internal pin	Notes
# 0	 GPIO0	ADC1                              
# 1	 GPIO1	ADC1                              Buzzer
# 2	 GPIO2	ADC1, boot mode / strapping pin   ST7335S-SPI/Rst (Không nối SPI/Rst với GPIO2 mà nối SPI/Rst với 3.3VDC = điện trở 10K)
# 3	 GPIO3	ADC1                              I2C/SDA
# 4	 GPIO4	ADC1, JTAG                        I2C/SCL
# 5	 GPIO5	JTAG                              ST7335S-SPI/Cs  OR  TM1637-clk
# 6	 GPIO6	JTAG                              ST7335S-SPI/Dc  OR  TM1637-dio
# 7	 GPIO7	JTAG                              ST7335S-SPI/Sclk/SCL
# 8	 GPIO8	Blue status_led (inverted), boot mode / strapping pin
# 9	 GPIO9	Boot mode / strapping pin, boot button
# 10 GPIO10	                                  ST7335S-SPI/Mosi/SDA
# 20 GPIO20                                   Hadware UART-RX for USB and Debug logging / <--> S21 tx
# 21 GPIO21                                   Hadware UART-TX for USB and Debug logging / <--> S21 rx
#                     ┌─────────┐                               
#                 ╔═══│ USB port│═══╗                            
# GPIO5  A5   D3  ║Ø  │         │  Ø║ 5V                        
# GPIO6  SDA  D4  ║Ø  │         │  Ø║ GND                       
# GPIO7  SCL  D5  ║Ø  └─────────┘  Ø║ 3V3                       
# GPIO8  SCK  D8  ║Ø ┌Boot┐ ┌RST─┐ Ø║ D2     A4 GPIO4                       
# GPIO9  MISO D9  ║Ø └────┘ └────┘ Ø║ D1     A3 GPIO3                       
# GPIO10 MOSI D10 ║Ø   ESP32-C3    Ø║ D0     A2 GPIO2                       
# GPIO20 RX   D7  ║Ø   Supermini   Ø║ ADC1-1 A1 GPIO1                      
# GPIO21 TX   D6  ║Ø               Ø║ ADC1-0 A0 GPIO0                        
#                 ║     ┌Capac.┐    ║                   
#                 ╚═════╧══════╧════╝  
#####################################################################################################
# Nếu không muốn dùng GPIO để điều khiển RES, bạn có thể:
# Kết nối một điện trở kéo lên (pull-up) 10kΩ từ chân RES đến 3.3V.
# Điều này đảm bảo RES ở mức HIGH mặc định, giúp ST7735S khởi động bình thường mà không cần điều khiển từ ESP32-C3.
# Lưu ý: Cách này chỉ hiệu quả nếu ST7735S tự động reset khi cấp nguồn (phụ thuộc vào thiết kế module).
substitutions:
  devicename: pgd-ac
  friendly_devicename: "AC phòng gia đình"
  pin_s21_rx: GPIO21
  pin_s21_tx: GPIO20
  pin_buzzer_io: GPIO1
  pin_ws2812_din: GPIO0
  pin_i2c_sda: GPIO3
  pin_i2c_scl: GPIO4
  # pin_tm1637_clk: GPIO5
  # pin_tm1637_dio: GPIO6
  pin_spi_cs: GPIO5
  pin_spi_dc: GPIO6
  pin_spi_sclk: GPIO7
  pin_spi_mosi: GPIO10

packages:
  main_config: !include common/.base_esp32.yaml
  device_config: !include common/.base_config.yaml
  device_status: !include common/.base_status.yaml
  scroll_display: !include common/scroll_display.yaml
esphome:
  includes:
    - custom_components/constants.h  # Include file hằng số
  on_boot:
    priority: -10
    then:
      - script.execute: update_led_color
# esp32:
  # variant: ESP32C3
  # board: lolin_c3_mini
  # framework:
    # type: arduino
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    
external_components:
  - source:
      type: local
      path: ./custom_components
    components: [ daikin_s21 ]

logger:
  baud_rate: 0
  logs:
    script: INFO

##### Blue LED onboard #####
# status_led:
  # pin:
    # number: GPIO8
    # inverted: false
    # ignore_strapping_warning: true
    
uart:
  - id: s21_uart
    tx_pin: ${pin_s21_rx}
    rx_pin: ${pin_s21_tx}
    baud_rate: 2400
    data_bits: 8
    parity: EVEN
    stop_bits: 2
    rx_buffer_size: 256 # Set other value --> error: [E][component:154]:   uart is marked FAILED: unspecified

daikin_s21:
  id: daikin_ctrl
  tx_uart: s21_uart
  rx_uart: s21_uart
  update_interval: 10s
  debug_protocol: true

climate:
  - platform: daikin_s21
    id: daikin_climate
    name: "Daikin"
    s21_id: daikin_ctrl
    visual:
      temperature_step: 1
      min_temperature: 18
      max_temperature: 30
    # supported_modes:
      # - "OFF"
      # - "HEAT_COOL"
      # - "COOL"
      # - "FAN_ONLY"
    supported_swing_modes:
      - "OFF"
      - "VERTICAL"
    has_presets: false
    update_interval: 10s
    on_control:
      lambda: |-
        auto ctrl = x;
        bool power_on = ctrl.get_mode().has_value() ? (ctrl.get_mode().value() != MODE_OFF) : id(daikin_ctrl).is_power_on();
        uint8_t mode = ctrl.get_mode().has_value() ? static_cast<uint8_t>(ctrl.get_mode().value()) : static_cast<uint8_t>(id(daikin_ctrl).get_climate_mode());
        float target_temp = ctrl.get_target_temperature().value_or(id(daikin_ctrl).get_setpoint());
        uint8_t fan_mode = ctrl.get_fan_mode().has_value() ? static_cast<uint8_t>(ctrl.get_fan_mode().value()) : static_cast<uint8_t>(id(daikin_ctrl).get_fan_mode());

        // Gửi lệnh điều khiển chính
        id(daikin_ctrl).set_daikin_climate_settings(power_on, static_cast<esphome::daikin_s21::DaikinClimateMode>(mode), target_temp, static_cast<esphome::daikin_s21::DaikinFanMode>(fan_mode));

        // Xử lý âm thanh và đèn dựa trên loại thay đổi
        if (ctrl.get_target_temperature().has_value() || ctrl.get_swing_mode().has_value() || ctrl.get_fan_mode().has_value()) {
          id(beep).execute("short");  // Thay đổi nhiệt độ, swing, hoặc fan mode
        } else if (ctrl.get_mode().has_value()) {
          id(beep).execute("long");  // Thay đổi chế độ
          id(var_mode) = mode;  // Cập nhật chế độ mới
          id(update_led_color).execute();  // Đổi màu đèn
        }

        // Gửi lệnh swing nếu có
        if (ctrl.get_swing_mode().has_value()) {
          auto swing = ctrl.get_swing_mode().value();
          esphome::daikin_s21::DaikinSwingMode dmode;
          if (swing == esphome::climate::CLIMATE_SWING_BOTH) {
            dmode = esphome::daikin_s21::DaikinSwingMode::BOTH;
          } else if (swing == esphome::climate::CLIMATE_SWING_VERTICAL) {
            dmode = esphome::daikin_s21::DaikinSwingMode::VERTICAL;
          } else if (swing == esphome::climate::CLIMATE_SWING_HORIZONTAL) {
            dmode = esphome::daikin_s21::DaikinSwingMode::HORIZONTAL;
          } else {
            dmode = esphome::daikin_s21::DaikinSwingMode::OFF;
          }
          id(daikin_ctrl).set_swing_mode(dmode);
        }
    on_state:
      then:
        - lambda: |-
            int current_mode = static_cast<int>(id(daikin_climate).mode);
            bool mode_changed = (current_mode != id(var_mode_last));
            float current_temp = id(daikin_climate).current_temperature;

            if (mode_changed) {
              id(var_mode_last) = current_mode;
              id(var_mode) = current_mode;

              if (current_mode == MODE_OFF) {
                id(beep).execute("short");  // Bíp ngắn đầu tiên
                delay(200);  // Đợi 200ms
                id(beep).execute("short");  // Bíp ngắn thứ hai
                // id(var_brightness) = 0.0;  // Tắt đèn
              } else {
                id(beep).execute("long");  // Bíp dài khi bật/chuyển chế độ
                id(update_led_color).execute();  // Đổi màu đèn
              }
            }

            if (!isnan(current_temp)) {
              int temp_int = static_cast<int>(current_temp);
              if (temp_int != id(var_temperature)) {
                id(var_temperature) = temp_int;
              }
            }

sensor:
  - platform: daikin_s21
    id: daikin_sensor
    s21_id: daikin_ctrl
    update_interval: 1min
    inside_temperature:
      name: "Room Temperature"
    outside_temperature:
      name: "Outside Temperature"
    coil_temperature:
      name: "Coil Temperature"
    fan_speed:
      name: "Fan Speed"

i2c:
  sda: ${pin_i2c_sda}
  scl: ${pin_i2c_scl}
  scan: true
  id: bus_a

spi:
  clk_pin: ${pin_spi_sclk}
  mosi_pin: ${pin_spi_mosi}

globals:
  - id: var_temperature
    type: int
    restore_value: yes
    initial_value: '25'
  - id: var_humidity
    type: int
    restore_value: yes
    initial_value: '-1'
  - id: var_mode
    type: int
    restore_value: yes
    initial_value: '0'
  - id: var_mode_last
    type: int
    restore_value: no
    initial_value: '0'
  - id: var_background_color
    type: Color
    restore_value: no
    initial_value: 'Color(0, 0, 0)'
  - id: var_text_color
    type: Color
    restore_value: no
    initial_value: 'Color(255, 255, 255)'

#########################################
output:
  - platform: ledc
    pin: ${pin_buzzer_io}
    frequency: 1000 Hz
    id: rtttl_out

rtttl:
  output: rtttl_out
  on_finished_playback:
    - logger.log: "Beep sound finished!"

script:
  - id: beep
    parameters:
      duration: string
    then:
      - rtttl.play: !lambda |-
          return (duration == "short") ? "short:d=16,o=5,b=100:c6" : "long:d=8,o=5,b=100:c6";

  - id: script_rtttl_play
    parameters:
      song: string
      volume: int
    mode: single
    then:
      - output.set_level:
          id: rtttl_out
          level: !lambda |-
            return (volume > 0) ? clamp(volume, 0, 100) / 100.0f : 1.0f;
      - rtttl.play:
          rtttl: !lambda |-
            return (song.find(":") == std::string::npos) ? ("song:d=16,o=5,b=100:" + song).c_str() : song.c_str();

  - id: update_led_color
    then:
      - lambda: |-
          switch (id(var_mode)) {
            case MODE_OFF: 
              id(var_background_color) = Color(0, 0, 0); // Nền đen
              id(var_text_color) = Color(128, 128, 128); // Chữ xám
              break;
            case MODE_AUTO:
              id(var_background_color) = Color(0, 150, 150); // Nền cyan đậm
              id(var_text_color) = Color(0, 0, 0); // Chữ đen
              break;
            case MODE_COOL: 
              id(var_background_color) = Color(0, 0, 220); // Nền xanh dương đậm
              id(var_text_color) = Color(255, 255, 255); // Chữ trắng
              break;
            case MODE_HEAT:
              id(var_background_color) = Color(220, 0, 0); // Nền đỏ đậm
              id(var_text_color) = Color(255, 255, 255); // Chữ trắng
              break;
            case MODE_DRY:
              id(var_background_color) = Color(255, 165, 0); // Nền vàng đậm
              id(var_text_color) = Color(0, 0, 0); // Chữ đen
              break;
            case MODE_FAN_ONLY:
              id(var_background_color) = Color(0, 120, 0); // Nền xanh lá đậm
              id(var_text_color) = Color(255, 255, 255); // Chữ trắng
              break;
            default:
              id(var_background_color) = Color(0, 0, 0); // Nền đen
              id(var_text_color) = Color(255, 255, 255); // Chữ trắng
              break;
          }

api:
  services:
    - service: play_rtttl
      variables:
        song_str: string
        volume: int
      then:
        - lambda: "id(script_rtttl_play).execute(song_str, volume);"

#########################################



############# Example Tones #############
            
# "two_short:d=4,o=5,b=100:16e6,16e6";
# "long:d=1,o=5,b=100:e6";
# "siren:d=8,o=5,b=100:d,e,d,e,d,e,d,e";
# "scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b";
# "star_wars:d=16,o=5,b=100:4e,4e,4e,8c,p,g,4e,8c,p,g,4e,4p,4b,4b,4b,8c6,p,g,4d#,8c,p,g,4e,8p";
# "The Simpsons:d=4,o=5,b=160:c.6,e6,f#6,8a6,g.6,e6,c6,8a,8f#,8f#,8f#,2g,8p,8p,8f#,8f#,8f#,8g,a#.,8c6,8c6,8c6,c6";
# "Indiana:d=4,o=5,b=250:e,8p,8f,8g,8p,1c6,8p.,d,8p,8e,1f,p.,g,8p,8a,8b,8p,1f6,p,a,8p,8b,2c6,2d6,2e6,e,8p,8f,8g,8p,1c6,p,d6,8p,8e6,1f.6,g,8p,8g,e.6,8p,d6,8p,8g,e.6,8p,d6,8p,8g,f.6,8p,e6,8p,8d6,2c6";
# "TakeOnMe:d=4,o=4,b=160:8f#5,8f#5,8f#5,8d5,8p,8b,8p,8e5,8p,8e5,8p,8e5,8g#5,8g#5,8a5,8b5,8a5,8a5,8a5,8e5,8p,8d5,8p,8f#5,8p,8f#5,8p,8f#5,8e5,8e5,8f#5,8e5,8f#5,8f#5,8f#5,8d5,8p,8b,8p,8e5,8p,8e5,8p,8e5,8g#5,8g#5,8a5,8b5,8a5,8a5,8a5,8e5,8p,8d5,8p,8f#5,8p,8f#5,8p,8f#5,8e5,8e5";
# "Entertainer:d=4,o=5,b=140:8d,8d#,8e,c6,8e,c6,8e,2c.6,8c6,8d6,8d#6,8e6,8c6,8d6,e6,8b,d6,2c6,p,8d,8d#,8e,c6,8e,c6,8e,2c.6,8p,8a,8g,8f#,8a,8c6,e6,8d6,8c6,8a,2d6";
# "Muppets:d=4,o=5,b=250:c6,c6,a,b,8a,b,g,p,c6,c6,a,8b,8a,8p,g.,p,e,e,g,f,8e,f,8c6,8c,8d,e,8e,8e,8p,8e,g,2p,c6,c6,a,b,8a,b,g,p,c6,c6,a,8b,a,g.,p,e,e,g,f,8e,f,8c6,8c,8d,e,8e,d,8d,c";
# "Xfiles:d=4,o=5,b=125:e,b,a,b,d6,2b.,1p,e,b,a,b,e6,2b.,1p,g6,f#6,e6,d6,e6,2b.,1p,g6,f#6,e6,d6,f#6,2b.,1p,e,b,a,b,d6,2b.,1p,e,b,a,b,e6,2b.,1p,e6,2b.";
# "Looney:d=4,o=5,b=140:32p,c6,8f6,8e6,8d6,8c6,a.,8c6,8f6,8e6,8d6,8d#6,e.6,8e6,8e6,8c6,8d6,8c6,8e6,8c6,8d6,8a,8c6,8g,8a#,8a,8f";
# "20thCenFox:d=16,o=5,b=140:b,8p,b,b,2b,p,c6,32p,b,32p,c6,32p,b,32p,c6,32p,b,8p,b,b,b,32p,b,32p,b,32p,b,32p,b,32p,b,32p,b,32p,g#,32p,a,32p,b,8p,b,b,2b,4p,8e,8g#,8b,1c#6,8f#,8a,8c#6,1e6,8a,8c#6,8e6,1e6,8b,8g#,8a,2b";
# "Bond:d=4,o=5,b=80:32p,16c#6,32d#6,32d#6,16d#6,8d#6,16c#6,16c#6,16c#6,16c#6,32e6,32e6,16e6,8e6,16d#6,16d#6,16d#6,16c#6,32d#6,32d#6,16d#6,8d#6,16c#6,16c#6,16c#6,16c#6,32e6,32e6,16e6,8e6,16d#6,16d6,16c#6,16c#7,c.7,16g#6,16f#6,g#.6";
# "MASH:d=8,o=5,b=140:4a,4g,f#,g,p,f#,p,g,p,f#,p,2e.,p,f#,e,4f#,e,f#,p,e,p,4d.,p,f#,4e,d,e,p,d,p,e,p,d,p,2c#.,p,d,c#,4d,c#,d,p,e,p,4f#,p,a,p,4b,a,b,p,a,p,b,p,2a.,4p,a,b,a,4b,a,b,p,2a.,a,4f#,a,b,p,d6,p,4e.6,d6,b,p,a,p,2b";
# "StarWars:d=4,o=5,b=45:32p,32f#,32f#,32f#,8b.,8f#.6,32e6,32d#6,32c#6,8b.6,16f#.6,32e6,32d#6,32c#6,8b.6,16f#.6,32e6,32d#6,32e6,8c#.6,32f#,32f#,32f#,8b.,8f#.6,32e6,32d#6,32c#6,8b.6,16f#.6,32e6,32d#6,32c#6,8b.6,16f#.6,32e6,32d#6,32e6,8c#6";
# "GoodBad:d=4,o=5,b=56:32p,32a#,32d#6,32a#,32d#6,8a#.,16f#.,16g#.,d#,32a#,32d#6,32a#,32d#6,8a#.,16f#.,16g#.,c#6,32a#,32d#6,32a#,32d#6,8a#.,16f#.,32f.,32d#.,c#,32a#,32d#6,32a#,32d#6,8a#.,16g#.,d#";
# "TopGun:d=4,o=4,b=31:32p,16c#,16g#,16g#,32f#,32f,32f#,32f,16d#,16d#,32c#,32d#,16f,32d#,32f,16f#,32f,32c#,16f,d#,16c#,16g#,16g#,32f#,32f,32f#,32f,16d#,16d#,32c#,32d#,16f,32d#,32f,16f#,32f,32c#,g#";
# "A-Team:d=8,o=5,b=125:4d#6,a#,2d#6,16p,g#,4a#,4d#.,p,16g,16a#,d#6,a#,f6,2d#6,16p,c#.6,16c6,16a#,g#.,2a#";
# "Flinstones:d=4,o=5,b=40:32p,16f6,16a#,16a#6,32g6,16f6,16a#.,16f6,32d#6,32d6,32d6,32d#6,32f6,16a#,16c6,d6,16f6,16a#.,16a#6,32g6,16f6,16a#.,32f6,32f6,32d#6,32d6,32d6,32d#6,32f6,16a#,16c6,a#,16a6,16d.6,16a#6,32a6,32a6,32g6,32f#6,32a6,8g6,16g6,16c.6,32a6,32a6,32g6,32g6,32f6,32e6,32g6,8f6,16f6,16a#.,16a#6,32g6,16f6,16a#.,16f6,32d#6,32d6,32d6,32d#6,32f6,16a#,16c.6,32d6,32d#6,32f6,16a#,16c.6,32d6,32d#6,32f6,16a#6,16c7,8a#.6";
# "Jeopardy:d=4,o=6,b=125:c,f,c,f5,c,f,2c,c,f,c,f,a.,8g,8f,8e,8d,8c#,c,f,c,f5,c,f,2c,f.,8d,c,a#5,a5,g5,f5,p,d#,g#,d#,g#5,d#,g#,2d#,d#,g#,d#,g#,c.7,8a#,8g#,8g,8f,8e,d#,g#,d#,g#5,d#,g#,2d#,g#.,8f,d#,c#,c,p,a#5,p,g#.5,d#,g#";
# "Gadget:d=16,o=5,b=50:32d#,32f,32f#,32g#,a#,f#,a,f,g#,f#,32d#,32f,32f#,32g#,a#,d#6,4d6,32d#,32f,32f#,32g#,a#,f#,a,f,g#,f#,8d#";
# "Smurfs:d=32,o=5,b=200:4c#6,16p,4f#6,p,16c#6,p,8d#6,p,8b,p,4g#,16p,4c#6,p,16a#,p,8f#,p,8a#,p,4g#,4p,g#,p,a#,p,b,p,c6,p,4c#6,16p,4f#6,p,16c#6,p,8d#6,p,8b,p,4g#,16p,4c#6,p,16a#,p,8b,p,8f,p,4f#";
# "MahnaMahna:d=16,o=6,b=125:c#,c.,b5,8a#.5,8f.,4g#,a#,g.,4d#,8p,c#,c.,b5,8a#.5,8f.,g#.,8a#.,4g,8p,c#,c.,b5,8a#.5,8f.,4g#,f,g.,8d#.,f,g.,8d#.,f,8g,8d#.,f,8g,d#,8c,a#5,8d#.,8d#.,4d#,8d#.";
# "LeisureSuit:d=16,o=6,b=56:f.5,f#.5,g.5,g#5,32a#5,f5,g#.5,a#.5,32f5,g#5,32a#5,g#5,8c#.,a#5,32c#,a5,a#.5,c#.,32a5,a#5,32c#,d#,8e,c#.,f.,f.,f.,f.,f,32e,d#,8d,a#.5,e,32f,e,32f,c#,d#.,c#";
# "MissionImp:d=16,o=6,b=95:32d,32d#,32d,32d#,32d,32d#,32d,32d#,32d,32d,32d#,32e,32f,32f#,32g,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,a#,g,2d,32p,a#,g,2c#,32p,a#,g,2c,a#5,8c,2p,32p,a#5,g5,2f#,32p,a#5,g5,2f,32p,a#5,g5,2e,d#,8d";
# "smbdeath:d=4,o=5,b=90:32c6,32c6,32c6,8p,16b,16f6,16p,16f6,16f.6,16e.6,16d6,16c6,16p,16e,16p,16c";
# "Monty P:d=4,o=5,b=200:f6,8e6,d6,8c#6,c6,8b,a#,8a,8g,8a,8a#,a,8g,2c6,8p,8c6,8a,8p,8a,8a,8g#,8a,8f6,8p,8c6,8c6,8p,8a,8a#,8p,8a#,8a#,8p,8c6,2d6,8p,8a#,8g,8p,8g,8g,8f#,8g,8e6,8p,8d6,8d6,8p,8a#,8a,8p,8a,8a,8p,8a#,2c6,8p,8c6";
# "Yaketysax:d=4,o=5,b=125:8d.,16e,8g,8g,16e,16d,16a4,16b4,16d,16b4,8e,16d,16b4,16a4,16b4,8a4,16a4,16a#4,16b4,16d,16e,16d,g,p,16d,16e,16d,8g,8g,16e,16d,16a4,16b4,16d,16b4,8e,16d,16b4,16a4,16b4,8d,16d,16d,16f#,16a,8f,d,p,16d,16e,16d,8g,16g,16g,8g,16g,16g,8g,8g,16e,8e.,8c,8c,8c,8c,16e,16g,16a,16g,16a#,8g,16a,16b,16a#,16b,16a,16b,8d6,16a,16b,16d6,8b,8g,8d,16e6,16b,16b,16d,8a,8g,g;"
# "YMCA:d=4,o=5,b=160:8c#6,8a#,2p,8a#,8g#,8f#,8g#,8a#,c#6,8a#,c#6,8d#6,8a#,2p,8a#,8g#,8f#,8g#,8a#,c#6,8a#,c#6,8d#6,8b,2p,8b,8a#,8g#,8a#,8b,d#6,8f#6,d#6,f.6,d#.6,c#.6,b.,a#,g#";
# "BarbieGirl:d=4,o=5,b=125:8g#,8e,8g#,8c#6,a,p,8f#,8d#,8f#,8b,g#,8f#,8e,p,8e,8c#,f#,c#,p,8f#,8e,g#,f#";
# "TakeOnMe:d=4,o=4,b=160:8f#5,8f#5,8f#5,8d5,8p,8b,8p,8e5,8p,8e5,8p,8e5,8g#5,8g#5,8a5,8b5,8a5,8a5,8a5,8e5,8p,8d5,8p,8f#5,8p,8f#5,8p,8f#5,8e5,8e5,8f#5,8e5,8f#5,8f#5,8f#5,8d5,8p,8b,8p,8e5,8p,8e5,8p,8e5,8g#5,8g#5,8a5,8b5,8a5,8a5,8a5,8e5,8p,8d5,8p,8f#5,8p,8f#5,8p,8f#5,8e5,8e5";

##########################################